In [1]:
import numpy as np
import pandas as pd
from sklearn import svm, metrics, tree
import matplotlib.pyplot as plt
from IPython.display import display
from astropy.table import Table
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
from sklearn.metrics import precision_recall_fscore_support
from sklearn.svm import SVC  

/Users/arthurbinda/anaconda/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
df= pd.read_csv('dadosProvaOnly.csv')

In [3]:
df.to_csv('dadosDiscretizados.csv', encoding='utf-8', index=False)

In [4]:
#Aqui eu tiro um aluno para teste
alunoEscolhido = 3356
dfAlunoSelecionado = df[df['Aluno'] == alunoEscolhido]

In [5]:
dfAlunoSelecionado

Aluno   Lab  PP_Delete       Duracao  PP_Paste  Qntd_Linhas  \
5192   3356  1021   0.210714  2.200522e+05  0.000000     2.500000   
5193   3356  1039   0.260833  8.588733e+04  0.002500    12.250000   
5194   3356  1069   0.370000  2.426500e+03  0.000000    11.500000   
5195   3356  1070   0.123750  6.240000e+02  0.008750     8.375000   
5196   3356  1079   0.200000  1.972552e+06  0.000000    13.000000   
5197   3356  1080   0.095000  7.940000e+02  0.005000    14.500000   
5198   3356  1111   0.213333  3.973000e+03  0.006667    13.666667   
5199   3356  1131   0.135833  1.407583e+03  0.041667    24.500000   
5200   3356  1137   0.100000  2.256000e+03  0.010000    19.000000   
5201   3356  1154   0.223333  2.215333e+03  0.016667    38.333333   
5202   3356  1165   0.145000  3.042000e+03  0.015000    16.000000   
5203   3356  1193   0.250000  1.597000e+03  0.005000    11.500000   
5204   3356  1201   0.600000  4.550000e+02  0.000000     2.000000   
5205   3356  1222   0.243333  6.236667e+02  0.006667     9.000000   

       Linhas_Log  Qntd_Linhas_Filtrado  Submissoes     Testes  Corretos  \
5192   106.857143              2.071429    1.714286   3.785714        14   
5193   328.333333              6.166667    1.250000   4.833333        12   
5194  1055.000000              7.000000    2.000000  11.000000         2   
5195   218.750000              5.875000    1.625000   9.375000         7   
5196   190.000000              6.000000    1.000000  12.000000         0   
5197   643.500000             10.500000    1.500000   4.500000         0   
5198   969.333333             10.000000    2.000000  40.666667         2   
5199   568.166667             19.750000    3.000000  14.083333        12   
5200  1086.000000             17.000000    3.000000  15.000000         0   
5201  1227.666667             34.000000    4.333333  30.333333         3   
5202   468.000000              8.500000    3.500000  19.000000         1   
5203   599.000000              9.500000    2.000000   7.000000         0   
5204    87.000000              0.000000    0.000000   0.000000         0   
5205   446.666667              7.000000    1.333333   9.666667         0   

      Incorretos  Branco      Nota  
5192           0       0  10.00000  
5193           0       0  10.00000  
5194           0       0  10.00000  
5195           0       5   5.83333  
5196           1       9   0.00000  
5197           1       5   0.00000  
5198           0       1   6.66667  
5199           0       0  10.00000  
5200           1      11   0.00000  
5201           0       0  10.00000  
5202           0      11   0.27500  
5203           2       0   0.00000  
5204           0      12   0.00000  
5205           3       0   0.00000

In [6]:
print(int(dfAlunoSelecionado.iloc[0]['Aluno']))

3356


In [7]:
df.drop(df.loc[df['Aluno'] == alunoEscolhido].index, inplace=True)

In [8]:
df = df.groupby(['Aluno'],as_index=False).agg({'Duracao': 'mean', 'Qntd_Linhas': 'mean', 'Qntd_Linhas_Filtrado': 'mean'
                                             , 'Testes': 'mean', 'Submissoes': 'mean', 'PP_Paste': 'mean'
                                             , 'PP_Delete': 'mean', 'Linhas_Log': 'mean', 'Nota':'mean'})

In [9]:
for index, row in df.iterrows():
    if(row['Nota'] >= 5.0):
        df.replace(row['Nota'], '1',inplace=True)
    else:
        df.replace(row['Nota'], '0',inplace=True)

df[['Nota']] = df[['Nota']].astype(int)

In [10]:
df[df['Nota'] != 1]

Aluno        Duracao Qntd_Linhas Qntd_Linhas_Filtrado    Testes  \
0     1085     762.062500       24.25               13.625    17.375   
2     1168  232050.500000         2.5                  2.5         1   
7     1373     137.000000           1                    1         2   
11    1502     600.750000        9.25                5.875         1   
19    1900    1191.500000           1                    3         0   
20    1913    1590.000000        18.5                    7       0.5   
21    1985     832.250000        9.25                    1       3.5   
22    2006   17227.404762     10.1667              4.69048   1.33333   
26    2139   13760.182944     10.4914              6.78348   6.96197   
30    2149   15576.464286           3              2.14286   2.03571   
31    2151   17384.359127     11.4444              6.70635   7.85516   
44    2363    5322.583333     8.33333              5.47222         1   
47    2377    1095.500000        13.5                    1         1   
50    2445   13068.696429     18.6667              12.3304   9.64187   
51    2490  517114.357143     11.5612              7.10544   4.65306   
57    2636    1143.000000       21.95                 15.5      28.7   
58    2639  377451.392857     7.35714              3.85714  0.428571   
59    2643  155004.626984     6.92063               4.4127   11.2063   
60    2646   23276.547619     11.3593              9.87229   25.1948   
62    2829     121.500000         9.5                    4       1.5   
63    2880      22.000000          17                    6         0   
67    2968  354534.652063       17.86              3.82413   22.2279   
74    3039   69123.333333     15.8333              11.8333         1   
82    3051   24176.277083     10.4926              7.09673   10.6412   
86    3055   53358.571429     7.70899              4.97487   10.4087   
93    3062  173301.442857     10.4714                    1   20.4762   
98    3067  689417.666667           7                    1         4   
151   3127  113991.027778     14.0556              10.0648   24.2037   
157   3133  119069.327778     13.4444              8.56389   13.4806   
193   3172   99810.077381     7.05952              3.60119     10.25   
..     ...            ...         ...                  ...       ...   
234   3214  331616.552484     13.0845              9.88846   15.0199   
260   3241  363547.631640     18.1201              8.83418   11.9853   
269   3257      67.250000         3.5                  3.5      1.25   
283   3274   13468.449735     11.7238              7.73386   7.74709   
288   3279   56562.281818     10.2499              7.84351   13.0411   
289   3280    1498.583333     14.6667              9.08333   4.33333   
290   3302      53.250000        52.5                 49.5      2.75   
341   3354    1079.390476      5.8619               3.1619   4.72381   
344   3358  209001.259028     11.8214              8.54992   9.85609   
349   3363     730.300000        9.75                    4      1.25   
385   3409   35062.910714     11.5893              9.04464   17.0982   
392   3424    1117.833333     7.91667              3.86111         1   
394   3426   89222.410450     14.3417              9.88466   12.7048   
401   3440   60184.765411     10.0884              7.42459   16.8294   
403   3442   90708.513889     7.79861              4.08472   10.9236   
412   3462  269817.750000        9.25                  8.5        37   
418   3481   90257.456494     10.4292              8.72165   8.65022   
419   3482   59301.725727     8.18162               5.8524   10.5864   
432   3504     414.928571     5.64286              3.03175    1.6746   
433   3506     351.000000          13                   12         7   
436   3510   18330.700000        14.5                    6      2.45   
442   3531   13456.388889     11.8199              7.79652   4.42769   
443   3532  382498.799444     25.2664              17.2181   9.26917   
444   3533    1020.000000          17        

In [11]:
def analisaAcerto(i,j):
    if(i[0] == j[0]):
        return 1
    else:
        return -1

# Aqui será feito: Treino com todas as medias, e o teste será acumulativo das medias com um aluno desconhecido

In [12]:
SemNota = list(df.columns.values)
SemNota.remove('Nota')
SemNota.remove('Aluno')
print(SemNota)

['Duracao', 'Qntd_Linhas', 'Qntd_Linhas_Filtrado', 'Testes', 'Submissoes', 'PP_Paste', 'PP_Delete', 'Linhas_Log']


In [13]:
X = df[SemNota].values
y = df['Nota'].values

In [14]:
print(X[0])

[762.0625 24.25 13.625 17.375 6.1875 0.001875 0.293125 516.75]


In [15]:
print(y.shape,X.shape)

(459,) (459, 8)


In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.25)

## Árvore de Decisão

In [17]:
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100, max_depth=3, min_samples_leaf=5)
clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [18]:
giniScore = clf_gini.score(X_test, y_test) 

In [19]:
y_pred = clf_gini.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[ 4, 13],
       [ 7, 91]])

In [20]:
y_pred = clf_gini.predict(X_test)
giniMCC = matthews_corrcoef(y_test, y_pred)

In [21]:
y_pred = clf_gini.predict(X_test)
giniF1 = precision_recall_fscore_support(y_test, y_pred, average='macro')

In [22]:
clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100, max_depth=3, min_samples_leaf=5)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [23]:
entroScore = clf_entropy.score(X_test, y_test) 

In [24]:
y_pred = clf_entropy.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[12,  5],
       [10, 88]])

In [25]:
y_pred = clf_entropy.predict(X_test)
entroMCC = matthews_corrcoef(y_test, y_pred)

In [26]:
y_pred = clf_entropy.predict(X_test)
entroF1 = precision_recall_fscore_support(y_test, y_pred, average='macro')

## Random Forest

In [27]:
clfRF = RandomForestClassifier(max_depth=2, random_state=0)

In [28]:
clfRF.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [29]:
rfScore = clfRF.score(X_test, y_test) 

In [30]:
y_pred = clfRF.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[ 7, 10],
       [ 2, 96]])

In [31]:
y_pred = clfRF.predict(X_test)
rfMCC = matthews_corrcoef(y_test, y_pred)

In [32]:
y_pred = clfRF.predict(X_test)
rfF1 = precision_recall_fscore_support(y_test, y_pred, average='macro')

In [33]:
gini = [giniScore,giniMCC,giniF1]
entro = [entroScore,entroMCC,entroF1]
rf = [rfScore,rfMCC,rfF1]

# Classificação de aprovação na matéria

In [34]:
rows = {'Classificador','Acuracia','MCC','F1Score','Realizado'}
tabela = pd.DataFrame(columns=rows)
tabela = tabela.append({'Classificador':'Tree Gini','Acuracia':giniScore,'MCC':giniMCC,'F1Score':giniF1,'Realizado': 'Treino'}
                       , ignore_index=True)
tabela = tabela.append({'Classificador':'Tree Entropy','Acuracia':entroScore,'MCC':entroMCC,'F1Score':entroF1,'Realizado': 'Treino'}
                       , ignore_index=True)
tabela = tabela.append({'Classificador':'Random Forest','Acuracia':rfScore,'MCC':rfMCC,'F1Score':rfF1,'Realizado': 'Treino'}
                       , ignore_index=True)

In [35]:
rows = {'Aluno','Iteracao','Esperado','Resultado','IteracaoCorreta','Classificador'}
resultados = pd.DataFrame(columns=rows)

In [36]:
dfResultadoIterado = pd.DataFrame()
dfResultadoIterado = dfAlunoSelecionado.groupby(['Aluno'],as_index=False).agg({'Duracao': 'mean', 'Qntd_Linhas': 'mean', 'Qntd_Linhas_Filtrado': 'mean'
                                             , 'Testes': 'mean', 'Submissoes': 'mean', 'PP_Paste': 'mean'
                                             , 'PP_Delete': 'mean', 'Linhas_Log': 'mean', 'Nota':'mean'})
aprovacao = dfResultadoIterado['Nota'][0]
for index, row in dfAlunoSelecionado.iterrows():
    if(aprovacao >= 5.0):
        dfAlunoSelecionado.replace(row['Nota'], '1',inplace=True)
    else:
        dfAlunoSelecionado.replace(row['Nota'], '0',inplace=True)

dfAlunoSelecionado[['Nota']] = dfAlunoSelecionado[['Nota']].astype(int)
dfAlunoSelecionado = dfAlunoSelecionado.reset_index(drop=True)

In [37]:
dfAlunoSelecionado['Nota'].values[0:1]

array([0])

In [38]:
dfAlunoIterado = pd.DataFrame()
for index, row in dfAlunoSelecionado.iterrows():
    dfAlunoIterado = dfAlunoIterado.append(row)
    alunoDaVez = row.get_value(0,'Aluno')
    if(index == 0):
        SemAluno = dfAlunoIterado
        del SemAluno['Lab']
        del SemAluno['Corretos']
        del SemAluno['Incorretos']
        del SemAluno['Branco']
        del SemAluno['Nota']
        dfTeste = SemAluno
        SemAluno = list(dfAlunoIterado.columns.values)
        SemAluno.remove('Aluno')
        dfTeste = dfAlunoIterado[SemAluno]
    else:
        dfAlunoIterado['Aluno'] = dfAlunoIterado['Aluno'].astype(int)
        dfAlunoIterado['Duracao'] = dfAlunoIterado['Duracao'].astype(int)
        dfAlunoIterado['Qntd_Linhas'] = dfAlunoIterado['Qntd_Linhas'].astype(int)
        dfAlunoIterado['Qntd_Linhas_Filtrado'] = dfAlunoIterado['Qntd_Linhas_Filtrado'].astype(int)
        dfAlunoIterado['Testes'] = dfAlunoIterado['Testes'].astype(int)
        dfAlunoIterado['Submissoes'] = dfAlunoIterado['Submissoes'].astype(int)
        dfAlunoIterado['PP_Paste'] = dfAlunoIterado['PP_Paste'].astype(float)
        dfAlunoIterado['PP_Delete'] = dfAlunoIterado['PP_Delete'].astype(float)
        dfAlunoIterado['Linhas_Log'] = dfAlunoIterado['Linhas_Log'].astype(int)
        
        dfAlunoIterado = dfAlunoIterado.groupby(['Aluno'],as_index=False).agg({'Duracao': 'mean', 'Qntd_Linhas': 'mean', 'Qntd_Linhas_Filtrado': 'mean'
                                     , 'Testes': 'mean', 'Submissoes': 'mean', 'PP_Paste': 'mean'
                                     , 'PP_Delete': 'mean', 'Linhas_Log': 'mean'})
        SemAluno = list(dfAlunoIterado.columns.values)
        SemAluno.remove('Aluno')
        dfTeste = dfAlunoIterado[SemAluno]
    print("iteracao: ",index," aluno: ",alunoDaVez)
    X_1 = dfTeste.values
    y_1 = dfAlunoSelecionado['Nota'].values[1:2]
    X_train, X_test, y_train, y_test = train_test_split(X_1, y_1, test_size=0.99)
    
    giniScore = clf_gini.score(X_test, y_test)

    y_pred = clf_gini.predict(X_test)
    giniCM = confusion_matrix(y_test, y_pred)

    y_pred = clf_gini.predict(X_test)
    giniMCC = matthews_corrcoef(y_test, y_pred)

    y_pred = clf_gini.predict(X_test)
    giniF1 = precision_recall_fscore_support(y_test, y_pred, average='macro')
    
    tabela = tabela.append({'Classificador':'Tree Gini','Acuracia':giniScore,'MCC':giniMCC,'F1Score':giniF1,'Realizado': index}
                       , ignore_index=True)
    
    iCorreto = analisaAcerto(y_test,y_pred)
    resultados = resultados.append({'Aluno':alunoDaVez,'Iteracao':index,'Esperado':y_test[0],'Resultado':y_pred[0],'IteracaoCorreta':iCorreto,'Classificador':'Tree Gini'}
                                   ,ignore_index=True)

    y_pred = clf_entropy.predict(X_test)
    entroCM = confusion_matrix(y_test, y_pred)

    y_pred = clf_entropy.predict(X_test)
    entroMCC = matthews_corrcoef(y_test, y_pred)

    y_pred = clf_entropy.predict(X_test)
    entroF1 = precision_recall_fscore_support(y_test, y_pred, average='macro')
    
    tabela = tabela.append({'Classificador':'Tree Entropy','Acuracia':entroScore,'MCC':entroMCC,'F1Score':entroF1,'Realizado': index}
                       , ignore_index=True)
    
    iCorreto = analisaAcerto(y_test,y_pred)
    resultados = resultados.append({'Aluno':alunoDaVez,'Iteracao':index,'Esperado':y_test[0],'Resultado':y_pred[0],'IteracaoCorreta':iCorreto,'Classificador':'Tree Entropy'}
                                   ,ignore_index=True)

    y_pred = clfRF.predict(X_test)
    rfCM = confusion_matrix(y_test, y_pred)

    rfScore = clfRF.score(X_test, y_test) 

    y_pred = clfRF.predict(X_test)
    rfMCC = matthews_corrcoef(y_test, y_pred)

    y_pred = clfRF.predict(X_test)
    rfF1 = precision_recall_fscore_support(y_test, y_pred, average='macro')
    
    tabela = tabela.append({'Classificador':'Random Forest','Acuracia':rfScore,'MCC':rfMCC,'F1Score':rfF1,'Realizado': index}
                       , ignore_index=True)
    
    iCorreto = analisaAcerto(y_test,y_pred)
    resultados = resultados.append({'Aluno':alunoDaVez,'Iteracao':index,'Esperado':y_test[0],'Resultado':y_pred[0],'IteracaoCorreta':iCorreto,'Classificador':'Random Forest'}
                                   ,ignore_index=True)

/Users/arthurbinda/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  after removing the cwd from sys.path.
/Users/arthurbinda/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:538: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
/Users/arthurbinda/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/arthurbinda/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


0
antes do index     Duracao  Qntd_Linhas  Qntd_Linhas_Filtrado  Testes  Submissoes  PP_Paste  \
0  152969.5            7                     4     3.5           1   0.00125   

   PP_Delete  Linhas_Log  
0   0.235774         217  
1
antes do index    Duracao  Qntd_Linhas  Qntd_Linhas_Filtrado  Testes  Submissoes  PP_Paste  \
0  77697.5            9                   5.5       7         1.5  0.000625   

   PP_Delete  Linhas_Log  
0   0.302887         636  
2
antes do index    Duracao  Qntd_Linhas  Qntd_Linhas_Filtrado  Testes  Submissoes  PP_Paste  \
0  39160.5          8.5                     5       8           1  0.004688   

   PP_Delete  Linhas_Log  
0   0.213318         427  
3
antes do index    Duracao  Qntd_Linhas  Qntd_Linhas_Filtrado  Testes  Submissoes  PP_Paste  \
0  1005856         10.5                   5.5      10           1  0.002344   

   PP_Delete  Linhas_Log  
0   0.206659       308.5  
4
antes do index    Duracao  Qntd_Linhas  Qntd_Linhas_Filtrado  Testes  Submis

In [39]:
tabela

Classificador       MCC  Acuracia Realizado  \
0       Tree Gini  0.197748  0.826087    Treino   
1    Tree Entropy  0.544889  0.869565    Treino   
2   Random Forest  0.517173  0.895652    Treino   
3       Tree Gini  0.000000  1.000000         0   
4    Tree Entropy  0.000000  0.869565         0   
5   Random Forest  0.000000  0.000000         0   
6       Tree Gini  0.000000  1.000000         1   
7    Tree Entropy  0.000000  0.869565         1   
8   Random Forest  0.000000  0.000000         1   
9       Tree Gini  0.000000  1.000000         2   
10   Tree Entropy  0.000000  0.869565         2   
11  Random Forest  0.000000  0.000000         2   
12      Tree Gini  0.000000  0.000000         3   
13   Tree Entropy  0.000000  0.869565         3   
14  Random Forest  0.000000  1.000000         3   
15      Tree Gini  0.000000  0.000000         4   
16   Tree Entropy  0.000000  0.869565         4   
17  Random Forest  0.000000  1.000000         4   
18      Tree Gini  0.000000  0.000000         5   
19   Tree Entropy  0.000000  0.869565         5   
20  Random Forest  0.000000  1.000000         5   
21      Tree Gini  0.000000  0.000000         6   
22   Tree Entropy  0.000000  0.869565         6   
23  Random Forest  0.000000  0.000000         6   
24      Tree Gini  0.000000  0.000000         7   
25   Tree Entropy  0.000000  0.869565         7   
26  Random Forest  0.000000  0.000000         7   
27      Tree Gini  0.000000  0.000000         8   
28   Tree Entropy  0.000000  0.869565         8   
29  Random Forest  0.000000  0.000000         8   
30      Tree Gini  0.000000  1.000000         9   
31   Tree Entropy  0.000000  0.869565         9   
32  Random Forest  0.000000  0.000000         9   
33      Tree Gini  0.000000  1.000000        10   
34   Tree Entropy  0.000000  0.869565        10   
35  Random Forest  0.000000  0.000000        10   
36      Tree Gini  0.000000  0.000000        11   
37   Tree Entropy  0.000000  0.869565        11   
38  Random Forest  0.000000  0.000000        11   
39      Tree Gini  0.000000  0.000000        12   
40   Tree Entropy  0.000000  0.869565        12   
41  Random Forest  0.000000  1.000000        12   
42      Tree Gini  0.000000  0.000000        13   
43   Tree Entropy  0.000000  0.869565        13   
44  Random Forest  0.000000  1.000000        13   

                                              F1Score  
0   (0.6193181818181819, 0.5819327731092437, 0.593...  
1   (0.7458455522971652, 0.801920768307323, 0.7684...  
2   (0.8417190775681342, 0.6956782713085234, 0.739...  
3                               (1.0, 1.0, 1.0, None)  
4                               (1.0, 1.0, 1.0, None)  
5                               (0.0, 0.0, 0.0, None)  
6                               (1.0, 1.0, 1.0, None)  
7                               (1.0, 1.0, 1.0, None)  
8                               (0.0, 0.0, 0.0, None)  
9                               (1.0, 1.0, 1.0, None)  
10                              (1.0, 1.0, 1.0, None)  
11                              (0.0, 0.0, 0.0, None)  
12                              (0.0, 0.0, 0.0, None)  
13                              (1.0, 1.0, 1.0, None)  
14                              (1.0, 1.0, 1.0, None)  
15                              (0.0, 0.0, 0.0, None)  
16                              (0.0, 0.0, 0.0, None)  
17                              (1.0, 1.0, 1.0, None)  
18                              (0.0, 0.0, 0.0, None)  
19                              (0.0, 0.0, 0.0, None)  
20                              (1.0, 1.0, 1.0, None)  
21                              (0.0, 0.0, 0.0, None)  
22                              (0.0, 0.0, 0.0, None)  
23                              (0.0, 0.0, 0.0, None)  
24                              (0.0, 0.0, 0.0, None)  
25                              (0.0, 0.0, 0.0, None)  
26                              (0.0, 0.0, 0.0, None)  
27                              (0.0, 0.0, 0.0, None)  
28                              (

In [40]:
print(giniCM)
print(entroCM)
print(rfCM)

[[0 1]
 [0 0]]
[[1]]
[[1]]


In [41]:
resultados

IteracaoCorreta  Classificador Aluno Esperado Resultado Iteracao
0                1      Tree Gini  3356        0         0        0
1                1   Tree Entropy  3356        0         0        0
2               -1  Random Forest  3356        0         1        0
3                1      Tree Gini  3356        0         0        1
4                1   Tree Entropy  3356        0         0        1
5               -1  Random Forest  3356        0         1        1
6                1      Tree Gini  3356        0         0        2
7                1   Tree Entropy  3356        0         0        2
8               -1  Random Forest  3356        0         1        2
9               -1      Tree Gini  3356        0         1        3
10               1   Tree Entropy  3356        0         0        3
11               1  Random Forest  3356        0         0        3
12              -1      Tree Gini  3356        0         1        4
13              -1   Tree Entropy  3356        0         1        4
14               1  Random Forest  3356        0         0        4
15              -1      Tree Gini  3356        0         1        5
16              -1   Tree Entropy  3356        0         1        5
17               1  Random Forest  3356        0         0        5
18              -1      Tree Gini  3356        0         1        6
19              -1   Tree Entropy  3356        0         1        6
20              -1  Random Forest  3356        0         1        6
21              -1      Tree Gini  3356        0         1        7
22              -1   Tree Entropy  3356        0         1        7
23              -1  Random Forest  3356        0         1        7
24              -1      Tree Gini  3356        0         1        8
25              -1   Tree Entropy  3356        0         1        8
26              -1  Random Forest  3356        0         1        8
27               1      Tree Gini  3356        0         0        9
28               1   Tree Entropy  3356        0         0        9
29              -1  Random Forest  3356        0         1        9
30               1      Tree Gini  3356        0         0       10
31               1   Tree Entropy  3356        0         0       10
32              -1  Random Forest  3356        0         1       10
33              -1      Tree Gini  3356        0         1       11
34              -1   Tree Entropy  3356        0         1       11
35              -1  Random Forest  3356        0         1       11
36              -1      Tree Gini  3356        0         1       12
37               1   Tree Entropy  3356        0         0       12
38               1  Random Forest  3356        0         0       12
39              -1      Tree Gini  3356        0         1       13
40               1   Tree Entropy  3356        0         0       13
41               1  Random Forest  3356        0         0       13